### ISSUE TITLE
Missing VENV_PREFIX in tasks/build.py when using pipenv as a management tool

### ISSUE THREAD

**Issue by josix** [Lee-W/cookiecutter-python-template#22]
It seems like the VENV_PREFIX is not imported when using pipenv as a management tool and this will cause `inv build` command will raise an error [here](https://github.com/Lee-W/cookiecutter-python-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/tasks/build.py#L15).

**Comment by Lee-W** [comment]
Thanks for report. Can't believe I ignore it for so long. Just fixed it 💪
