### ISSUE TITLE
Add a general Dockerfile for poetry-managed python project

### ISSUE THREAD

**Issue by RainrainWu** [Lee-W/cookiecutter-python-template#9]
How about adding a default Dockerfile? I often need to check the process of installing poetry and pipx while dockerizing a service, a default general Dockerfile is a great help.

For example, like this:

```
FROM python:3.8-slim

ENV PYTHONUNBUFFERED=1
ENV PATH=$PATH:/root/.local/bin
WORKDIR /project

COPY . /project/

    # Install pipx
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --user pipx --no-warn-script-location && \
    python3 -m pipx ensurepath && \
    # Install poetry
    apt-get update -y && \
    apt-get install curl -y && \
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && \
    . $HOME/.poetry/env && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

```

**Comment by Lee-W** [comment]
Sounds good to me. I thought of this. Just don't have enough time to do so ATM. Feel free to send me a PR. Notice that both `poetry` and `pipenv` are supported by this template, you might want to do something like https://github.com/Lee-W/cookiecutter-python-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/tasks/env.py#L9. Also, I'd like to make this an option like "build_pypi_package" https://github.com/Lee-W/cookiecutter-python-template/blob/master/cookiecutter.json#L12 You can remove the undeeded Dockerfile through https://github.com/Lee-W/cookiecutter-python-template/blob/master/hooks/post_gen_project.py
